apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: signoz-vector

resources:
- kustomization/system-kustomization.yaml
- kustomization/signoz-kustomization.yaml
- signoz/helm/helmrepo.yaml
- signoz/helm/helmrelease.yaml
- system/observability/helm/helmrepo.yaml
- system/observability/helm/helmrelease.yaml
- system/observability/daemonset/vector-daemonset.yaml
- system/deployments/dummy-log-gen.yaml
- system/namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: signoz-values
  files:
  - values.yaml=signoz/values/signoz.yaml
- name: otel-collector-values
  files:
  - values.yaml=system/observability/values/otel-collector.yaml
- name: jaeger-values
  files:
  - values.yaml=system/observability/values/jaeger.yaml
- name: victoriametrics-values
  files:
  - values.yaml=system/observability/values/victoriametrics.yaml
- name: clickhouse-values
  files:
  - values.yaml=signoz/values/clickhouse.yaml