apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  namespace: elk-int
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: gen
        image: coljurten/dummy-java-loggen:latest
        imagePullPolicy: Always
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.signoz-vector.svc.cluster.local:4317"
        - name: OTEL_SERVICE_NAME
          value: "dummy-java-loggen"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
