apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: elk-int
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
rules:
- apiGroups: [ "" ]
  resources:
  - pods
  - namespaces
  - nodes
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: elk-int
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elk-int
data:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true

    # A straightforward container log input (works broadly in local clusters)
    filebeat.inputs:
      - type: filestream
        id: k8s-container-logs
        paths:
          - /var/log/containers/*.log
        parsers:
          - container: ~

    processors:
      - add_kubernetes_metadata: {}

      # Optional: drop Filebeat's own logs if they loop back
      - drop_event:
          when:
            equals:
              kubernetes.container.name: "filebeat"

    output.logstash:
      hosts: ["logstash-logstash.elk-int.svc.cluster.local:5044"]

    logging.level: info
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: elk-int
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
      annotations:
        # Enable hints autodiscover; not strictly required but handy
        co.elastic.logs/enabled: "true"
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.15.0
        args: [ "-c", "/etc/filebeat.yml", "-e" ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          subPath: filebeat.yml
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: filebeat-config
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
