apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: signoz-repo
  namespace: signoz-vector
spec:
  interval: 30m
  url: https://charts.signoz.io
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: clickhouse-repo
  namespace: signoz-vector
spec:
  type: oci
  interval: 30m
  url: oci://registry-1.docker.io/bitnamicharts
